#!/usr/bin/env ruby
require 'jay_flavored_markdown'
require 'optparse'

module JayFlavoredMarkdown
  output_type = 'markdown'

  OptionParser.new do |opt|
    opt.version = VERSION
    opt.separator('Options:')
    opt.on('-d', '--debug', 'Start in debug mode'){$JAY_DEBUG = true}
    opt.on('--output=type', ['html','markdown'], 'html | markdown (default:markdown)'){|v| output_type = v}
    opt.on_tail('-v', '--version', 'Show version'){puts opt.ver;exit}
    opt.on_tail('-h', '--help', 'Show this message'){puts opt;exit}

    begin
      opt.parse!(ARGV)
    rescue OptionParser::ParseError => e
      puts e
      exit 1
    end
  end

  case output_type
  when 'html'
    puts <<-EOF
    <style>
      ol {list-style-type: none;}
    </style>
    EOF
    puts JayFlavoredMarkdownConverter.new(gets(nil)).content
  when 'markdown'
    puts JayFlavoredMarkdownToPlainTextConverter.new(gets(nil)).content
  end
end
